### ISSUE TITLE
Oauth2 and Guzzle

### ISSUE THREAD

**Issue by CMCDragonkai** [keeguon/oauth2-php#5]
Hello,

Do you have any documentation on how to use this library? Since Guzzle supports Oauth1, and this is Oauth2? Is it possible to use both Guzzle and this library to communicate to both twitter and facebook? Would I need to load guzzle indepedently?

**Comment by wmurphy** [comment]
A basic use example would also help us!

**Comment by keeguon** [comment]
Hey guys,

I'm currently writing a basic example for you I'll post this later today ;).

Félix Bellanger
122 Rue Marcadet
75018 Paris, France
Email: felix.bellanger@gmail.com
Twitter: @keeguon http://twitter.com/keeguon
Phone: +33.6.78.53.28.15

**Comment by wmurphy** [comment]
Thank you very much.

**Comment by CMCDragonkai** [comment]
An example on Oauth1 and Oauth2 would be awesome.

**Comment by keeguon** [comment]
Hey guys,

Sorry for replying so late but between work and Valentines day, couldn't really find the time before now to finish writing my example. Without further due here it is:

``` php
<?php

if (false === class_exists('Symfony\Component\ClassLoader\UniversalClassLoader', false)) {
  require_once __DIR__.'/../vendor/Symfony/Component/ClassLoader/UniversalClassLoader.php';
}

use Symfony\Component\ClassLoader\UniversalClassLoader;

$loader = new UniversalClassLoader();
$loader->registerNamespaces(array(
    'Symfony'       => __DIR__.'/../vendor'
  , 'Guzzle'        => __DIR__.'/../vendor/guzzle/src'
  , 'OAuth2'        => array(__DIR__.'/../src', __DIR__)
));
$loader->register();


/* Create your client, this MUST be done before each of your requests */
$client = new \OAuth2\Client('yourclientid', 'yourclientsecret', array('site' => 'https://api.example.com'));

/* Redirect the user to the authorization page on the OAuth2 provider */
$authorizeParams = array('state' => 'somestate'); // Basically all additionnal params you want to pass to the service provider or required by them
header('Location: '.$client->authCode()->authorizeUrl(array_merge(array('redirect_uri' => 'https://yourwebsite.com/auth/example/callback', $authorizeParams))));

/* After being redirected to your callback page for the service */
if (isset($_GET['error'])) {
  // Handle the OAuth2 error
}

$accessToken = $client->authCode()->getToken($_GET['code'], array_merge(array('redirect_uri' => 'https://yourwebsite.com/auth/example/callback'), array('parse' => 'json')), array('mode' => 'query'));
if ($accessToken->isExpired()) {
  $accessToken = $accessToken->refresh();
}

// From this point on you should be able to make requests against the OAuth2 provider using the $accessToken object
try {
  $response       = $accessToken->get('/someendpoint', array('parse' => 'json'));
  $parsedResponse = $response->parse();
} catch (\Exception $e) {
  // If the request fails it throws an exception so you have to handle it however you want
}
```

I took a lot of assumption and this is a very basic example but if you want more details you can dig into the code itself or read the tests which are also a great way to learn what you can do. I also wrote another library which make use of this library to authenticate against some services you can find it here: https://github.com/Keeguon/MultiPass. If you want more details on how to authenticate against OAuth 1.0 there's a pretty good PECL extenstion which does that very well that you can find here: http://pecl.php.net/package/oauth and the documentation is pretty decent.

If you're still having trouble I would be really happy to answer more complex questions either here or if you want me to take a little bit more time we could also plan a hangout or something.

Peace.

**Comment by wmurphy** [comment]
Hi! Thanks a lot for the example, it was very helpful.

We've been looking into the code, and found it very welll written, but had doubts implementing it with server to server authentication. For what we've seen, we probably need to implement a new strategy, or probably dig into MultiPass. 

Whats your recommendation for server to server auth?

**Comment by keeguon** [comment]
Hey,

What do you mean by server to server auth because you could probably work
something out with my example, as for MultiPass you could add your own
strategy depending on your needs. Also you should know I'm planning to
break down the MultiPass strategies into multiple repositories in a near
future that way you'll only have to require the strategy you want via
composer instead of loading unused strategies.

Félix Bellanger
122 Rue Marcadet
75018 Paris, France
Email: felix.bellanger@gmail.com
Twitter: @keeguon http://twitter.com/keeguon
Phone: +33.6.78.53.28.15

**Comment by wmurphy** [comment]
By server to server, I mean no user intervention, i think the name is "two-legged OAuth validation".

The problem we're finding is that we don't have a user/pass y the "client" server, just the Id and Secret.

**Comment by keeguon** [comment]
Re,

Concerning two-legged OAuth 1.0, I guess the official PECL extension must
support it as long as the service provider supports it.

As for OAuth 2.0 this type of authentication is now called the "Client
Credentials Grant" and is described here:
http://tools.ietf.org/html/rfc6749#section-4.4 and should be supported by
my library as long as you pass the right options when calling
"\OAuth2\Client#getToken" method to obtain your token in order to make
requests. Of course the service provider must support this type of
authentication.

Cheers.

Félix Bellanger
122 Rue Marcadet
75018 Paris, France
Email: felix.bellanger@gmail.com
Twitter: @keeguon http://twitter.com/keeguon
Phone: +33.6.78.53.28.15
